controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true # for running in gazebo

    diff_controller:
      type: diff_drive_controller/DiffDriveController
    
    # publish state of the joint to get wheel transform (not super important, good to have though)
    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    publish_rate: 50.0 # should probably set to match the manager's update rate. oh well
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05
    use_stamped_vel: false # false for now so future me can deal with this